budget/urls.py
from django.urls import path
from . import views

app_name = 'budget'

urlpatterns = [
    path('', views.project_list , name='list'),
    path('add/', views.ProjectCreateView.as_view() , name='create'),
    path('<slug>/', views.project_detail , name='detail'),
    path('<slug>/delete/', views.project_delete , name='delete'),
]

budget_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from login.views import (
    register,
    register_success,
    logout_page,
    redirect_to_home,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register),
    path('register/success/', register_success),
    path('accounts/',  include('django.contrib.auth.urls'), name='login'),
    path('logout/', logout_page, name='logout'),
    path('', redirect_to_home),
    path('home/', include('budget.urls')),
    # path(, home),
    
    
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class RegistrationForm(forms.Form):
 
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Username"), error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password (again)"))
 
    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))
 
    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data

login/views.py
from django.shortcuts import render

# Create your views here.
#views.py
from login.forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
 
@csrf_protect
def register(request):
    if request.user.is_authenticated is False:
        if request.method == 'POST':
            form = RegistrationForm(request.POST)
            if form.is_valid():
                user = User.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
                email=form.cleaned_data['email']
                )
                return HttpResponseRedirect('/accounts/login/')
        else:
            form = RegistrationForm()
            variables =  {
                'form' : form, 
            }
        return render(request, 'registration/register.html', variables)
    else:
        return HttpResponseRedirect('/home/')
 
def register_success(request):
    return render_to_response(
    'registration/success.html',
    )
 
def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')

def redirect_to_home(request):
    return HttpResponseRedirect('/home/')

login/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
    <title>{% block title %}{% endblock %}</title>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <!-- <link rel="stylesheet" type="text/css" href=" {# static 'css/home.css' #}"> -->
</head>
<body>
      <div class="topnav" id="myTopnav">
            <a href="{% url 'budget:list' %}" class="home">Budget</a>
            {% if request.user.is_authenticated %}
            <a href="#">Logout</a>
            <a href="{% url 'budget:create' %}">Add Project </a>
            {% endif %}
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                  <i class="fa fa-bars"></i>
            </a>
      </div>
    {% block body %}
    {% endblock %}
      <script type="text/javascript">
            function myFunction() {
                  var x = document.getElementById("myTopnav");
                  if (x.className === "topnav") {
                        x.className += " responsive";
                  } else {
                        x.className = "topnav";
                  }
            }
    </script>
</body>

</html>